### ISSUE TITLE
Support --debug flag that prints detailed information when executing a command 

### ISSUE THREAD

**Issue by kschulst** [statisticsnorway/dapla-team-cli#54]
It would be neat if commands could support some kind of `--debug` flag (on a general basis) that would print debug information to the console. Debug information could be e.g. requests to and responses from the the dapla-team-api.

**Comment by nicolst** [comment]
`--loglevel debug`/`-v debug` enables debug logging. Can also implement logs for info/critical/warn etc. levels

#204
